name: Create Android Release

permissions:
  contents: write

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Decode release signing key
      run: |
        echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 -d > release.keystore
        echo "RELEASE_KEYSTORE_PATH=$(realpath release.keystore)" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew build
      env:
        SIGNING_KEY_FILE: ${{ env.RELEASE_KEYSTORE_PATH }}
        SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Set app version env var
      run: |
        VERSION_NAME=$(grep -oP 'versionName\s*"\K[^"]+' app/build.gradle)
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

    - name: Upload binaries to a release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: app/build/outputs/apk/release/*.apk
        tag_name: "v${{ env.VERSION_NAME }}"
