name: Create Android Release

permissions:
  contents: write

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Get latest release info from official
      id: get_info
      run: |
        release_info=$(curl -sL "https://api.github.com/repos/LeadRDRK/UmaPatcher/releases/latest" | jq -r '{tag: .tag_name, url: .html_url}')
        echo "latest_tag=$(echo $release_info | jq -r .tag)" >> $GITHUB_OUTPUT
        echo "release_url=$(echo $release_info | jq -r .url)" >> $GITHUB_OUTPUT

    - name: Upload binaries to a release
      uses: softprops/action-gh-release@v2
      with:
        body: |
          ${{ steps.get_info.outputs.release_url }}
        files: app/build/outputs/apk/release/*.apk
        tag_name: ${{ steps.get_info.outputs.latest_tag }}
